# Generated by Django 3.2 on 2023-06-06 05:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tests_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default=tests_app.models.generate_random_string, max_length=10, unique=True, verbose_name='Логин')),
            ],
        ),
        migrations.CreateModel(
            name='TestIQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Баллы')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iq_test', to='tests_app.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestEQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=5, verbose_name='Ответ')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eq_test', to='tests_app.test')),
            ],
        ),
    ]
